FROM docker.io/ubuntu:16.04
MAINTAINER Jacek Danecki <jacek.danecki@intel.com>

COPY neo /root/neo
RUN apt-get -y update; apt-get install -y --allow-unauthenticated cmake g++ git wget pkg-config ninja-build clang-4.0 libtsan0
RUN cd /root; git clone https://github.com/intel/gmmlib gmmlib ;\
    git clone --depth 1 -b release-1.7.0 https://github.com/google/googlemock gmock ; \
    git clone --depth 1 -b release-1.7.0 https://github.com/google/googletest gtest ; \
    git clone --depth 1 https://github.com/KhronosGroup/OpenCL-Headers khronos ; \
    cd neo/scripts/igc ; ./prepare.sh ; cd ../../.. ; \
    mkdir build; cd build ; cmake -G Ninja -DBUILD_TYPE=Release -DUSE_TSAN=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0 ../neo ; ninja -j `nproc` run_mt_unit_tests ; ./bin/igdrcl_mt_tests
CMD ["/bin/bash"]
